USE VetClinic
GO

ALTER TABLE VetClinic.dbo.OwnerInfo
ADD
	SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START DEFAULT GETDATE(),
	SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	period for system_time (SysStartTime, SysEndTime);

ALTER TABLE VetClinic.dbo.OwnerInfo
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.OwnerInfo_History))
GO

ALTER TABLE VetClinic.dbo.PatientInfo
ADD
	SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START DEFAULT GETDATE(),
	SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	period for system_time (SysStartTime, SysEndTime);

ALTER TABLE VetClinic.dbo.PatientInfo
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.PatientInfo_History))
GO